### ISSUE TITLE
There's no way to clear the value of `oauthContext` unless refresh the whole page

### ISSUE THREAD

**Issue by yifanplanet** [stripe/stripe-apps#649]
**Describe the bug**
By following the OAuth workflow provided by Stripe: [Add authorization flows](https://stripe.com/docs/stripe-apps/oauth#retrieve-an-access-token), I'm able to successfully access the values in `oauthContext` from my app. 

***The problem:***
However, the values in `oauthContext` never clears even if I navigate to other pages on Stripe and it just remains the same, which causes the `useEffect` statement (that relies on `oauthContext` as argument) keeps trigger whenever I navigate on Stripe dashboard:
```
const code = oauthContext?.code || '';
const verifier = oauthContext?.verifier || '';
useEffect(() => {
    if (code && verifier) {
      getTokenFromAuthServer({code, verifier, mode}).then(tokenData => {
        if (tokenData) {
          setTokenData(tokenData);
          saveTokenData({userID, tokenData});
        }
      });
    }
  }, [code, verifier, mode, userID]);
```

The only way to clear the values in `oauthContext` is to refresh the whole Stripe dashboard page, which our Stripe app does not have access to. And `oauthContext` is the only parameter the app has access to to identify if it's a callback from OAuth URL.

**Expected behavior**
`oauthContext` should be reset whenever the page's url changes when navigating to other pages on Stripe dashboard.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]

**Comment by yifanplanet** [comment]
> 

Hi @cchalstrom-stripe , thanks for your suggestion and but the Stripe app doesn't work like that: 
Whenever a user navigates to a different page on Stripe, the current opened Stripe app will gets completely restarted, which results in all the React states and variables recreated (including the `tokenData` you mentioned above). And at the same time, the `oauthContext` never gets recreated and Stripe is always sending the same `oauthContext` to the Stripe app unless user manually refreshes the page.

**Comment by cchalstrom-stripe** [comment]
Ah, I see.  That is helpful, thanks.

Currently there are 2 ways to persist data across page navigations:
- Use [secret store](https://stripe.com/docs/stripe-apps/store-secrets).  You could then check for the token there first before trying to get it from the auth server.
- Use the `stripe.dashboard.drawer.default` viewport.

The OAuth context is provided to you is meant to just be there to read at any time if the OAuth handshake was successful, similar to other user data.  So in the meantime I would suggest using secret store and checking there before requesting the token again.

We will keep this in mind in the future though because we may want to offer more robust ways to maintain state across page navigations.
