### ISSUE TITLE
Add onPress event to ContextView externalLink property

### ISSUE THREAD

**Issue by omerfranco** [stripe/stripe-apps#657]
The externalLink property in ContextView has only 'label' and 'href' attributes.
We need the onPress event of this link

**Comment by ericfrank-stripe** [comment]
Hi @omerfranco, the `externalLink` property is only meant to be used as a normal HTML link that opens a tab in a new window, which is why it has the external arrow icon. We don't provide an `onPress` event so that it can't be repurposed for button-like events. If you'd like to include a link with an `onPress` handler in the header of your app, you can try the `actions` property:

```
import {
  Button,
  ContextView,
  Link,
} from "@stripe/ui-extension-sdk/ui";

<ContextView
  title="My view"
  actions={<Link onPress={() => console.log('test')}>My link</Link>}
>
```

More documentation on `ContextView` here: https://stripe.com/docs/stripe-apps/components/contextview
