### ISSUE TITLE
Question: Unsupported resource for Data Store entity

### ISSUE THREAD

**Issue by tyrelchambers** [stripe/stripe-apps#765]
**What's happening**
We have access to the Data Store Beta and we're trying to write to a particular Data Store entity. When the `object` property within the `resource` object is set to **invoice**, this error is raised: `Unsupported resource for Data Store entity: invoice`.
```
"resource": {
    "object": "customer", <---- "invoice"
    "id": "cus_KzgJRvwZVmlgcB" <----- "in_1234"
  }
```

When invoices are finalized, are they read-only in any way that might prevent updating them in the Data Store?

So far this is the only Stripe resource that is raising this error and I'm wondering if there are some nuances surrounding the use of this resource in the Data Store.

Thanks!

**Comment by mattpatt-stripe** [comment]
Hey @tyrelchambers, thanks for opening this issue! For our initial iteration of Data Store we've built support for Stripe's core API resources and payment methods, and we plan to add support for new resources as we go. This is largely because there are so many resources available in Stripe's API, and some resources are easier to support than others.

In this case, it was easy to add support for Invoices, and so that's what we've done! This change should be shipped today, and I'll post an update here once it's available.

Cheers,
-Matt

**Comment by tyrelchambers** [comment]
Thanks for the update! I really appreciate all the hard work that goes into shipping these features. Thanks for the quick turn-around!

**Comment by mattpatt-stripe** [comment]
Invoices should be available in the Data Store API now 😎

```
❯ curl https://api.stripe.com/v1/datastore/entities \
  -u "${STRIPE_API_KEY}:" \
  -d "bucket[type]"=app \
  -d "bucket[app]"=acct_redacted \
  -d "resource[object]"=invoice \
  -d "resource[id]"=in_1M4pFhJ9ZzvaxoYINI81LhyV \
  -d name=test_entity \
  -d "data[foo]"=bar | jq

{
  "id": "dataentity_5110PmO1T04K62Gdnwj1J9ZzvaxoYI",
  "object": "datastore.entity",
  "bucket": {
    "app": "acct_redacted",
    "type": "app"
  },
  "created": 1668633473,
  "data": {
    "foo": "bar"
  },
  "livemode": false,
  "name": "test_entity",
  "resource": {
    "id": "in_1M4pFhJ9ZzvaxoYINI81LhyV",
    "object": "invoice"
  }
}
```

**Comment by dariodjuric** [comment]
@mattpatt-stripe, thanks for adding support for invoices in such a short time.

We're now in the process of thorough testing of our app, and we've noticed that _quotes_ and _subscriptions_ are not supported either. In addition, we were planning to have similar functionality for _charges_ as well.

Would it be difficult to add support for those objects?

If it's too complicated to add, we'll have to disable those object types in the app. But if it's easy to add like the invoices, we'd appreciate that!

**Comment by mattpatt-stripe** [comment]
Hey @dariodjuric, subscription and quote should be available now as well 😄

```
❯ curl https://api.stripe.com/v1/datastore/entities \
  -u "${STRIPE_API_KEY}:" 
  -d "bucket[type]"=app \
  -d "bucket[app]"=acct_redacted \
  -d "resource[object]"=subscription \
  -d "resource[id]"=sub_1M5ZxfJ9ZzvaxoYIp87sN7w2 \
  -d name=test_entity \
  -d "data[foo]"=bar | jq

{
  "id": "dataentity_5110Kz1DF0fO62RoTpx1J9ZzvaxoYI",
  "object": "datastore.entity",
  "bucket": {
    "app": "acct_redacted",
    "type": "app"
  },
  "created": 1668798757,
  "data": {
    "foo": "bar"
  },
  "livemode": false,
  "name": "test_entity",
  "resource": {
    "id": "sub_1M5ZxfJ9ZzvaxoYIp87sN7w2",
    "object": "subscription"
  }
}
```

Because of the upcoming Thanksgiving holiday in the US, this is probably the last update we'll be able to make for a little while. But if there are other resources that would be helpful, please continue surfacing them and we can take a look!

Cheers,
-Matt
