### ISSUE TITLE
SignInView component add target option for the Sign in button

### ISSUE THREAD

**Issue by Matthieu-OD** [stripe/stripe-apps#769]
**Is your feature request related to a problem? Please describe.**

When I'm using the [SignInView](https://stripe.com/docs/stripe-apps/components/signinview) component, I'm not able to choose the target on the `<a>` tag of the button Sign in. It is frustrating because my login flow happens on one tab only. With `target="_blank"`, I have two tabs at the end of my login process.

![image](https://user-images.githubusercontent.com/59685483/203481990-a94eaf41-461c-446b-905e-0f3c66af9afa.png)

**Describe the solution you'd like**

I want to be able to change the attribute `target` of the `Sign in` button of the `SignInView` component.

**Describe alternatives you've considered**

Before, I used a simple `Link` component, which allowed me to choose a different target option. After reading the documentation, I migrated to the SignInView component to follow the best practices.

![image](https://user-images.githubusercontent.com/59685483/203482388-4539c99d-4bdb-4714-a4ae-6ce0536d5d69.png)

**Additional context**

**Comment by cchalstrom-stripe** [comment]
Hello, thanks for opening this issue.  I'd like to learn a bit more about your use case.  This isn't configurable at the moment because we want to have a consistent sign in experience across all apps.  It's something we are open to changing if there is a strong case for it, though.  Why does your login flow need to happen in a single tab?

**Comment by cchalstrom-stripe** [comment]
Would it solve your use case if we allow a custom `target` but disallow `_self`, `_top`, and `_parent`?

**Comment by Matthieu-OD** [comment]
Thank you for being so quick to answer, and sorry for the delay.

We are doing it in one tab to be consistent with what we have on our app. If a user wants to go back he/she can still use the backward button or click on the `return to` button on the connect.stripe.com page.

What are the reasons why you don't want to allow `_self` in target?

**Comment by cchalstrom-stripe** [comment]
Hey, no problem!  The main reason is we want to have a consistent sign-in experience with Stripe apps in the Stripe dashboard.  We want the external site to open in a new tab so that users don't need to leave Stripe to complete the sign-in.

I'll close this out for now as we don't plan to allow `_self` for sign-in view at this time.

If anyone is following this issue, please give a 👍  on the issue if you have a use case for this so we can understand how much demand there is for it.

**Comment by Matthieu-OD** [comment]
@cchalstrom-stripe, after trying to implement your Sign in component with the target="_blank" I can further explain why it's not working for me.

In my flow, when a user clicks on the `Sign in` or `Sign up` button, I'm using SSO to create an account/log him in (in my app). Once done, the user is directly redirected to his stripe dashboard. So he never leaves stripe.

Everything happens in one tab.

If the `Sign in` button opens a new tab, I won't be able to close it, and therefore my flow can't work because the user will have two tabs with his stripe dashboard open.

I totally get your point of making sure the user never leaves stripe. That's why if any links leave the stripe dashboard, they have a target set to `_blank`.

**Comment by cchalstrom-stripe** [comment]
Hi @Matthieu-OD thanks for clarifying that.  We discussed and this is something we are planning to support.

**Comment by ericfrank-stripe** [comment]
The `target` property is now available in SDK `8.6.0`: https://www.npmjs.com/package/@stripe/ui-extension-sdk/v/8.6.0
