### ISSUE TITLE
Missing documentation related to backend webhooks configuration

### ISSUE THREAD

**Issue by benfoster** [stripe/stripe-apps#805]
## Your Problem

The stripe CLI includes the ability to define a webhook endpoint, for example:

```
stripe apps add                                  
✔ webhook
Webhook endpoint URL: https://example.com
Webhook endpoint API version: *
Enter webhook endpoint enabled events separated by comma (","): charge.succeeded
```

The manifest is then updated accordingly:

```json
  "app_backend": {
    "webhooks": [
      {
        "url": "https://example.com",
        "enabled_events": [
          "charge.succeeded"
        ],
        "api_version": "*"
      }
    ]
  },
```

However, it is unclear what the purpose is of defining webhooks in this way and there seems to be restrictions in the enabled events (the schema doesn't allow `charge.succeeded`, for example.

My understanding is that after installing an app, providing the necessary [permissions](https://stripe.com/docs/stripe-apps/reference/permissions) are defined, we can create a webhook endpoint that subscribes to connected account events. What is the purpose of defining webhooks in the app instead?

## Existing Documentation URLs (If applicable)

**Comment by Joshua206-2** [comment]
Yeah your right. I'm learning everything all at once, for the time. and I'm
noticing little hiccups, that if not simply fixed, will stop the entire
system. What do you suggest I do with the webhooks?bi hit waiting until
it's ready to be added, but what can I do to take care of it?

**Comment by chaves-stripe** [comment]
hi @benfoster @Joshua206-2! This feature is still in development, and for now we will be reverting the ability to add webhooks via the manifest/CLI. You will not lose any functionality as developers and instead you can follow the instructions here (https://stripe.com/docs/stripe-apps/build-backend?public-private=public#receiving-events-webhooks) to register webhooks and listen for events.  

Let me know if you have any questions! If you are seeing issues with uploading your app due to the `app_backend` in your app manifest, I suggest removing it from the JSON as you can get all of the same functionality from the webhooks registered in the Dashboard.
