### ISSUE TITLE
Rarely, the SettingsView component of our app does not load

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#964]
Rarely, for some inexplicable and inconsistent reason, my SettingsView does not load.  We have multiple fail-safes in-place for the loading of our settings.  If settings from our server can't be loaded, in the very worst scenario, we provide the user an error message, with an option to reload their settings.  However, the SettingsView never arrives to the point where this error could be triggered.  It doesn't seem there's any error reporting in place to handle this rare error.  There's nothing in the console to indicate there was an error loading the app, but by all indications, there was certainly an error loading our SettingsView.

![image](https://github.com/stripe/stripe-apps/assets/5982592/0ef3d973-000f-47a6-8bb6-56b68416c283)

![image](https://github.com/stripe/stripe-apps/assets/5982592/562f7a34-0146-4341-b772-8e681c788aac)

Has anyone else seen this "White Screen of Death" error in the SettingsView?

**Comment by bensontrent** [comment]
![image](https://github.com/stripe/stripe-apps/assets/5982592/ce5319e3-3960-4b7b-941d-bb60162f6da7)
This is a pretty big issue. Why is my settings view not loading?

**Comment by bensontrent** [comment]
The settings view only loads (if it loads as blank) if I refresh my browser.

**Comment by bensontrent** [comment]
After a refresh, I see the proper interrace:

![image](https://github.com/stripe/stripe-apps/assets/5982592/c5334a38-148f-4aa3-901d-ccf680cf5795)

**Comment by kovalev-stripe** [comment]
Thank you for reporting the issue @bensontrent.
We agree that the problem looks quite serious and we will try to prioritise its investigation.

**Comment by kovalev-stripe** [comment]
Hey @bensontrent,

Sorry for a bit delayed response. 

After spending some time investigating the problem, I have to say that unfortunately I have not been able to figure out what the root cause of the problem is, but at the same time several problematic areas have been identified. Therefore, we would like to ask you to provide us with additional debugging information in case you do manage to reproduce the problem again.

In particular, it would be great if you can:
 * check network requests to relevant endpoints[^1]
	* you can use this `/sandbox|ajax\/apps|v1/tailor/` filter [in the search box of Network panel of Chrome Dev tools][1]
 * inspect [the state of the React Components tree][2]
	 * Do you see the `AppSettingsContent` node in the tree? If so, is it a leaf node or do you also see `TailorViewportV2` as its child node?
	 * Sharing the screenshot of the React Tree would be very helpful as it will help us to localise the problem

Thank you in advance.

[^1]: Our current theory is that pending network requests to either `GET /v1/tailor/install` or `GET /ajax/apps/devmode` could lead to an empty setting screen.




[1]: https://github.com/stripe/stripe-apps/assets/97477677/ecb7371d-c087-423a-9755-be095d155cdb
[2]: https://github.com/stripe/stripe-apps/assets/97477677/40588bd9-fc9e-494c-be96-918285e11adc

**Comment by bensontrent** [comment]
I've not seen this issue in recent weeks. From my experience, a dramatic improvement has been made in the Stripe Apps platform since I reported this issue. I'm closing this issue.
